name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Rust toolchain
        uses: greenbone/actions/setup-rust@v3
        with:
          rust-version: stable
      - name: Build
        run: make build
      - name: Run tests
        run: make test

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Rust toolchain
        uses: greenbone/actions/setup-rust@v3
        with:
          rust-version: stable
      - name: Run Rust linter
        run: make clippy

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Rust toolchain
        uses: greenbone/actions/setup-rust@v3
        with:
          rust-version: stable
      - name: Check code formatting
        run: make fmt

  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - name: Set up Rust
        uses: greenbone/actions/setup-rust@v3
        with:
          rust-version: stable
          components: llvm-tools-preview
      - name: Generate coverage report
        run: make cover
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-report
          path: |
            target/coverage/html
            target/coverage/lcov.info
          if-no-files-found: error
      - name: Submit test coverage to codecov.io
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: greenbone/gvm-report-service
          fail_ci_if_error: false
